# Generated by Django 6.0.5 on 2026-09-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=255)),
                ('op_correcta', models.CharField(max_length=100)),
                ('op_falsa1', models.CharField(max_length=100)),
                ('op_falsa2', models.CharField(max_length=100)),
                ('fk_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.nivel')),
            ],
        ),
    ]
