# Generated by Django 6.0.5 on 2026-09-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.IntegerField()),
                ('fecha_completado', models.DateField(auto_now_add=True)),
                ('fk_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.nivel')),
            ],
        ),
    ]
